services:
  db:
    image: mariadb
    container_name: ${PROJECT_NAME}_db
    restart: ${COMPOSE_RESTART_POLICY}
    environment:
      - MARIADB_USER=${DB_USER_NAME}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_ROOT_PASSWORD=${DB_USER_ROOT_PASSWORD}
      - TZ=${TIME_ZONE}
    networks:
      - default
    