services:
  node:
    build:
      context: ../www/frontend/
      dockerfile: build/Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: ${PROJECT_NAME}-node
    user: node
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../www/frontend/code:/var/www/frontend
    networks:
      - default
